// <auto-generated />
namespace e_market.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class phaseone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phaseone));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020949333_phaseone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
